account.msg = welcome to the tola bank Account production application
account.build-version =3

account.mailDetails.hostName = production-accouns@tola.com
account.mailDetails.port = 9002
account.mailDetails.from = default-accouns@tola.com
account.mailDetails.subject = Your account detail form tola bank production environments

account.activeBranches[0] = phnom penh
account.activeBranches[1] = kampong thom
account.activeBranches[2] = svay reang
