account.msg = welcome to the tola bank Account default application
account.build-version =3

account.mailDetails.hostName = default-accouns@tola.com
account.mailDetails.port = 9000
account.mailDetails.from = default-accouns@tola.com
account.mailDetail.subject = Your account detail form tola bank Default environments

account.activeBranches[0] = phnom penh
account.activeBranches[1] = kampong thom
account.activeBranches[2] = kampong chnang
