account.msg = welcome to the tola bank Account dev application
account.build-version =2

account.mailDetails.hostName = dev-accouns@tola.com
account.mailDetail.port = 9001
account.mailDetail.from = dev-accouns@tola.com
account.mailDetail.subject = Your account detail form tola bank dev environments

account.activeBranches[0] = kampong cham
account.activeBranches[1] = kampong thom
account.activeBranches[2] = kampong chnang