loan.build-version = 3

loan.mailDetails.hostName = production-loan@tola.com
loan.mailDetails.port = 9002
loan.mailDetails.from = production-loan@tola.com
loan.mailDetail.subject = Your account detail form tola bank dev environments

loan.activeBranches[0] = kampong cham
loan.activeBranches[1] = kampong thom
loan.activeBranches[2] = kampong chnang
