loan.build-version = 1

loan.mailDetails.hostName = dev-loan@tola.com
loan.mailDetails.port = 9001
loan.mailDetails.from = dev-loan@tola.com
loan.mailDetail.subject = Your account detail form tola bank dev environments

loan.activeBranches[0] = kampong cham
loan.activeBranches[1] = kampong thom
loan.activeBranches[2] = kampong chnang
