loan.msg = welcome to the tola bank Loan production application
loan.build-version =3

loan.mailDetails.hostName = production-loans@tola.com
loan.mailDetails.port = 9002
loan.mailDetails.from = default-loans@tola.com
loan.mailDetails.subject = Your loan  detail form tola bank production environments

loan.activeBranches[0] = phnom penh
loan.activeBranches[1] = kampong thom
loan.activeBranches[2] = svay reang
