account.msg = welcome to the tola bank Loan default application
account.build-version =3

loan.mailDetails.hostName = default-loans@tola.com
loan.mailDetails.port = 9000
loan.mailDetails.from = default-loans@tola.com
loan.mailDetail.subject = Your loan  detail form tola bank Default environments

loan.activeBranches[0] = phnom penh
loan.activeBranches[1] = kampong thom
loan.activeBranches[2] = kampong chnang
