account.msg = welcome to the tola bank Account production application
account.build-version =3

account.mailDetails.hostName = production-accouns@tola.com
account.mailDetail.port = 9002
account.mailDetail.from = default-accouns@tola.com
account.mailDetail.subject = Your account detail form tola bank production environments

account.activeBranches[0] = phnom penh
account.activeBranches[1] = kampong thom
account.activeBranches[2] = svay reang